import os, re, time, asyncio, statistics
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import httpx
from bs4 import BeautifulSoup
from fastapi import FastAPI, Query
from fastapi.responses import HTMLResponse, JSONResponse, FileResponse
from sqlalchemy import create_engine, text

BASE = Path(__file__).resolve().parent
DATABASE_URL = os.getenv('DATABASE_URL', 'sqlite:///./flowscope.db')
if DATABASE_URL.startswith('postgres://'):
    DATABASE_URL = DATABASE_URL.replace('postgres://', 'postgresql+psycopg://', 1)
elif DATABASE_URL.startswith('postgresql://') and '+psycopg' not in DATABASE_URL:
    DATABASE_URL = DATABASE_URL.replace('postgresql://', 'postgresql+psycopg://', 1)
engine = create_engine(DATABASE_URL, pool_pre_ping=True)
COLLECT_INTERVAL = max(60, int(os.getenv('COLLECT_INTERVAL_SECONDS', '60')))
COINGLASS_API_KEY = os.getenv('COINGLASS_API_KEY', '').strip()

app = FastAPI(title='FlowScope BTC Cloud')

SCHEMA = '''
CREATE TABLE IF NOT EXISTS snapshots (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ts BIGINT NOT NULL,
  tf VARCHAR(8) NOT NULL,
  price DOUBLE PRECISION,
  price_move DOUBLE PRECISION,
  spot_z DOUBLE PRECISION,
  futures_z DOUBLE PRECISION,
  oi_z DOUBLE PRECISION,
  oi_change DOUBLE PRECISION,
  funding_z DOUBLE PRECISION,
  funding_rate DOUBLE PRECISION,
  etf_daily DOUBLE PRECISION,
  etf_3d DOUBLE PRECISION,
  etf_5d_momentum DOUBLE PRECISION,
  regime VARCHAR(64),
  confidence VARCHAR(16)
)
'''
SQLITE_SCHEMA = SCHEMA.replace('INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY','INTEGER PRIMARY KEY AUTOINCREMENT')


def init_db():
    with engine.begin() as conn:
        conn.execute(text(SQLITE_SCHEMA if DATABASE_URL.startswith('sqlite') else SCHEMA))
        conn.execute(text('CREATE INDEX IF NOT EXISTS idx_snapshots_tf_ts ON snapshots(tf, ts)'))


def mean(xs): return sum(xs)/len(xs) if xs else 0.0

def stdev(xs):
    if len(xs) < 2: return 1.0
    s = statistics.pstdev(xs)
    return s if s > 1e-12 else 1.0

def z_last(xs):
    if len(xs) < 10: return 0.0
    hist=xs[:-1]
    return (xs[-1]-mean(hist))/stdev(hist)

def kline_delta(k):
    vol=float(k[5]); taker=float(k[9]); return 2*taker-vol

def flow_class(z):
    if z>1.5: return 'Strong Buy','pos'
    if z>.45: return 'Buy','pos'
    if z<-1.5: return 'Strong Sell','neg'
    if z<-.45: return 'Sell','neg'
    return 'Neutral','neu'

def oi_class(z):
    if z>1.5: return 'Sharp Rise','warn'
    if z>.4: return 'Rising','warn'
    if z<-1.5: return 'Sharp Drop','pos'
    if z<-.4: return 'Falling','pos'
    return 'Stable','neu'

def funding_class(z):
    if z>1.5: return 'High','warn'
    if z>.4: return 'Positive','warn'
    if z<-1.5: return 'Strong Negative','neg'
    if z<-.4: return 'Negative','neg'
    return 'Neutral','neu'

def etf_class(daily, d3, momentum):
    if daily is None: return 'Unavailable','off'
    if daily>0 and d3>0 and momentum>0: return 'Strong Inflow','pos'
    if daily>0 or d3>0: return 'Inflow','pos'
    if daily<0 and d3<0 and momentum<0: return 'Strong Outflow','neg'
    if daily<0 or d3<0: return 'Outflow','neg'
    return 'Neutral','neu'

def regime_engine(price_move, spot_z, fut_z, oi_z, fund_z, etf_daily=None, etf_3d=None):
    r=dict(regime='Mixed Market', confidence='LOW', title='Смешанный рынок',
           text='Потоки пока не формируют чистую закономерность.',
           confirm='Ждём согласования Spot / Futures / OI / Funding.', cancel='—')
    if price_move>0 and spot_z>.45 and fut_z>-.45 and oi_z<1.5 and fund_z<1.5:
        r=dict(regime='Healthy Spot Growth',confidence='MEDIUM',title='Здоровый спотовый рост',
               text='Рост подтверждается спотовым спросом, а плечи пока не выглядят экстремально перегретыми.',
               confirm='Spot остаётся сильным, OI не ускоряется экстремально.',
               cancel='Spot слабеет, а Futures / OI начинают доминировать.')
    if price_move>0 and spot_z<.45 and fut_z>1.0 and oi_z>1.0 and fund_z>.6:
        r=dict(regime='Futures-driven Rise',confidence='HIGH',title='Перегретый рост на фьючерсах',
               text='Цена растёт преимущественно за счёт деривативов. Spot не подтверждает движение, OI и Funding повышают уязвимость структуры.',
               confirm='Spot остаётся слабым, а импульс Futures начинает затухать.',
               cancel='Появляется устойчивый сильный Spot-покупатель.')
    if price_move>=0 and spot_z<-.45 and oi_z>.7 and fund_z>.5:
        r=dict(regime='Distribution',confidence='MEDIUM',title='Распределение',
               text='Цена держится, но Spot ухудшается на фоне повышенного leverage. Риск разворота вниз растёт.',
               confirm='Spot CVD продолжает снижаться, цена перестаёт обновлять хаи.',
               cancel='Возвращается сильный Spot-спрос.')
    if price_move<0 and fut_z<-.7 and oi_z>.5:
        r=dict(regime='Short Build-up',confidence='MEDIUM',title='Наращивание шортов',
               text='Цена падает вместе с агрессивными продажами Futures и ростом OI. Новые позиции поддерживают снижение.',
               confirm='OI продолжает расти на снижении.', cancel='Spot абсорбирует продажи, OI перестаёт расти.')
    if price_move<0 and oi_z<-1.1:
        r=dict(regime='Long Flush',confidence='MEDIUM',title='Вынос лонгов',
               text='Цена падает вместе с резким снижением OI. Это очистка плеч, но ещё не LONG-сигнал.',
               confirm='Цена стабилизируется, Spot-продажи ослабевают.', cancel='OI снова растёт вместе с продажами.')
    if price_move<=0 and spot_z>.7 and oi_z<.3 and fund_z<.5:
        r=dict(regime='Accumulation / Absorption',confidence='MEDIUM',title='Накопление / абсорбция',
               text='Цена не растёт, но Spot показывает покупателя без перегрева плеч. Возможен сценарий накопления.',
               confirm='Spot продолжает покупать, цена перестаёт обновлять лои.', cancel='Spot разворачивается вниз.')
    if price_move>=0 and spot_z>.6 and oi_z<-.5 and fund_z<.3:
        r=dict(regime='Healthy Deleveraging',confidence='HIGH',title='Здоровое снижение плеч',
               text='Цена держится при сильном Spot, а OI / Funding охлаждаются. Плечи очищаются без потери спроса.',
               confirm='Spot сохраняет спрос после снижения OI.', cancel='Spot также начинает слабеть.')
    return r

async def get_json(client,url,headers=None):
    r=await client.get(url,headers=headers or {},timeout=15.0)
    r.raise_for_status(); return r.json()

async def fetch_farside(client):
    try:
        r=await client.get('https://farside.co.uk/btc/',headers={'User-Agent':'Mozilla/5.0'},timeout=15.0)
        r.raise_for_status()
        soup=BeautifulSoup(r.text,'html.parser')
        rows=[]
        for tr in soup.find_all('tr'):
            cells=[c.get_text(' ',strip=True) for c in tr.find_all(['td','th'])]
            if not cells: continue
            if re.match(r'^\d{2}\s+[A-Za-z]{3}\s+\d{4}$',cells[0]):
                raw=cells[-1].replace(',','').strip()
                if raw in {'-',''}: continue
                neg=raw.startswith('(') and raw.endswith(')')
                raw=raw.strip('()$ ')
                try:
                    val=float(raw); val=-val if neg else val
                    rows.append((cells[0],val))
                except: pass
        if not rows: return {'status':'Unavailable','daily':None,'d3':None,'momentum5':None,'date':None}
        vals=[v for _,v in rows]
        daily=vals[-1]
        d3=sum(vals[-3:]) if len(vals)>=3 else sum(vals)
        prev5=mean(vals[-10:-5]) if len(vals)>=10 else mean(vals[:-5]) if len(vals)>5 else 0.0
        last5=mean(vals[-5:]) if len(vals)>=5 else mean(vals)
        momentum=last5-prev5
        status,cls=etf_class(daily,d3,momentum)
        return {'status':status,'cls':cls,'daily':daily,'d3':d3,'momentum5':momentum,'date':rows[-1][0]}
    except Exception as e:
        return {'status':'Unavailable','cls':'off','daily':None,'d3':None,'momentum5':None,'date':None,'error':str(e)[:160]}

async def fetch_market(tf='4h'):
    tf=tf if tf in {'1h','4h','1d','1w'} else '4h'
    limit=120 if tf=='1w' else 100
    bybit_tf={'1h':'1h','4h':'4h','1d':'1d','1w':'1d'}[tf]
    errors=[]
    async with httpx.AsyncClient(follow_redirects=True) as client:
        tasks=[
            get_json(client,f'https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval={tf}&limit={limit}'),
            get_json(client,f'https://fapi.binance.com/fapi/v1/klines?symbol=BTCUSDT&interval={tf}&limit={limit}'),
            get_json(client,f'https://api.bybit.com/v5/market/open-interest?category=linear&symbol=BTCUSDT&intervalTime={bybit_tf}&limit=60'),
            get_json(client,'https://api.bybit.com/v5/market/funding/history?category=linear&symbol=BTCUSDT&limit=100'),
            fetch_farside(client)
        ]
        res=await asyncio.gather(*tasks,return_exceptions=True)
    spot,fut,oi,funding,etf=res
    if isinstance(spot,Exception): errors.append('Binance spot: '+str(spot)); spot=None
    if isinstance(fut,Exception): errors.append('Binance futures: '+str(fut)); fut=None
    if isinstance(oi,Exception): errors.append('Bybit OI: '+str(oi)); oi=None
    if isinstance(funding,Exception): errors.append('Bybit funding: '+str(funding)); funding=None
    if isinstance(etf,Exception): errors.append('Farside: '+str(etf)); etf={'status':'Unavailable','cls':'off','daily':None,'d3':None,'momentum5':None}
    if not spot or not fut:
        return {'ok':False,'errors':errors,'etf':etf}
    sdel=[kline_delta(k) for k in spot]; fdel=[kline_delta(k) for k in fut]
    sz,fz=z_last(sdel),z_last(fdel); sst,scl=flow_class(sz); fst,fcl=flow_class(fz)
    p0,p1=float(spot[-2][4]),float(spot[-1][4]); pm=(p1/p0-1)*100
    oi_state={'status':'Unavailable','cls':'off','z':0.0,'change':None}
    try:
        arr=list(reversed([float(x['openInterest']) for x in oi['result']['list']]))
        changes=[(arr[i]/arr[i-1]-1)*100 for i in range(1,len(arr))]
        oz=z_last(changes); och=changes[-1]; ost,ocl=oi_class(oz)
        oi_state={'status':ost,'cls':ocl,'z':oz,'change':och}
    except Exception as e: errors.append('OI parse: '+str(e))
    fund_state={'status':'Unavailable','cls':'off','z':0.0,'rate':None}
    try:
        arr=list(reversed([float(x['fundingRate']) for x in funding['result']['list']]))
        fuz=z_last(arr); cur=arr[-1]; ust,ucl=funding_class(fuz)
        fund_state={'status':ust,'cls':ucl,'z':fuz,'rate':cur}
    except Exception as e: errors.append('Funding parse: '+str(e))
    reg=regime_engine(pm,sz,fz,oi_state['z'],fund_state['z'],etf.get('daily'),etf.get('d3'))
    return {'ok':True,'ts':int(time.time()),'tf':tf,'price':p1,'priceMove':pm,
            'spot':{'status':sst,'cls':scl,'z':sz,'delta':sdel[-1]},
            'futures':{'status':fst,'cls':fcl,'z':fz,'delta':fdel[-1]},
            'oi':oi_state,'funding':fund_state,'etf':etf,'regime':reg,'errors':errors}


def save_snapshot(d):
    if not d.get('ok'): return
    q=text('''INSERT INTO snapshots(ts,tf,price,price_move,spot_z,futures_z,oi_z,oi_change,funding_z,funding_rate,etf_daily,etf_3d,etf_5d_momentum,regime,confidence)
              VALUES(:ts,:tf,:price,:pm,:sz,:fz,:oz,:och,:uz,:ur,:ed,:e3,:e5,:reg,:conf)''')
    with engine.begin() as conn:
        conn.execute(q,dict(ts=d['ts'],tf=d['tf'],price=d['price'],pm=d['priceMove'],sz=d['spot']['z'],fz=d['futures']['z'],oz=d['oi']['z'],och=d['oi']['change'],uz=d['funding']['z'],ur=d['funding']['rate'],ed=d['etf'].get('daily'),e3=d['etf'].get('d3'),e5=d['etf'].get('momentum5'),reg=d['regime']['regime'],conf=d['regime']['confidence']))

async def collector():
    await asyncio.sleep(3)
    while True:
        try:
            for tf in ('1h','4h','1d'):
                d=await fetch_market(tf); save_snapshot(d)
        except Exception as e:
            print('collector error',repr(e),flush=True)
        await asyncio.sleep(COLLECT_INTERVAL)

@app.on_event('startup')
async def startup():
    init_db(); asyncio.create_task(collector())

@app.get('/healthz')
async def healthz(): return {'ok':True,'time':int(time.time())}

@app.get('/api/state')
async def state(tf: str=Query('4h')):
    d=await fetch_market(tf)
    if d.get('ok'): save_snapshot(d); return d
    return JSONResponse(d,status_code=502)

@app.get('/api/history')
async def history(tf:str='4h',limit:int=200):
    limit=max(1,min(limit,1000))
    with engine.begin() as conn:
        rows=conn.execute(text('SELECT ts,price,spot_z,futures_z,oi_z,oi_change,funding_z,funding_rate,etf_daily,regime,confidence FROM snapshots WHERE tf=:tf ORDER BY ts DESC LIMIT :lim'),{'tf':tf,'lim':limit}).mappings().all()
    return {'ok':True,'rows':[dict(r) for r in reversed(rows)]}

@app.get('/manifest.webmanifest')
async def manifest(): return FileResponse(BASE/'manifest.webmanifest',media_type='application/manifest+json')
@app.get('/sw.js')
async def sw(): return FileResponse(BASE/'sw.js',media_type='application/javascript')
@app.get('/',response_class=HTMLResponse)
async def index(): return (BASE/'index.html').read_text(encoding='utf-8')
